// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int greaterThanHalf = 0;
		int lessThanOrEqualHalf = 0;

		for (int i = 0; i< N; i++); {
			double random = Math.random();
			if (random > 0.5) {
				greaterThanHalf = greaterThanHalf + 1; }
				 else { lessThanOrEqualHalf = lessThanOrEqualHalf + 1; }	}
        System.out.println( "> 0.5 " + greaterThanHalf + " times");
		System.out.println( "<= 0.5 " + lessThanOrEqualHalf + " times");

		if (lessThanOrEqualHalf !=0) { 
			System.out.println("Ratio: " + (double) greaterThanHalf / lessThanOrEqualHalf);
			
		}


	}
}
