// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int greaterThanHalf = 0;
		int lessThanOrEqualHalf = 0;

		for (int i = 0; i < N; i++); {
			double random = Math.random();
			if (random > 0.5) {
				greaterThanHalf++; }
				 else { lessThanOrEqualHalf++; }	}
        System.out.println( "> 0.5: " + greaterThanHalf + " times");
		System.out.println( "<= 0.5: " + lessThanOrEqualHalf + " times");

		if (lessThanOrEqualHalf !=0) { 
		double ratio = (double) greaterThanHalf / lessThanOrEqualHalf;
		System.out.println( "Ratio: " + ratio);
			
		}


	}
}
